[project]
name = "python-react"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "microdot>=2.3.2",
    "mypy>=1.16.0",
]
